name = "mundial2026"
compatibility_date = "2025-01-01"
pages_build_output_dir = "public"

# Powiązanie bazy D1 — database_id uzupełnisz po `wrangler d1 create`
[[d1_databases]]
binding = "DB"
database_name = "mundial2026"
database_id = "ed5808a8-3da5-4c46-b70c-df1cf7fc1779"
